name: 'Print message'
description: 'Prints a message to the console.'
branding:
  icon: 'check-circle'
  color: 'orange'
inputs:
  message: 
    description: "The message to print"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Printing message..."
      run: |
          echo ${env:INPUT_MESSAGE}
      shell: pwsh
