name: Calling action using sha
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jessehouwing/techorama-actions-demo@e0641204cab477bfb7c91d94718e60f0aedcb1a5
        with:
          message: "Good job!"


# e0641204cab477bfb7c91d94718e60f0aedcb1a5
